name: Install GAMS on Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-gams:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GAMS
        run: |
          $url = "https://d37drm4t2jghv5.cloudfront.net/distributions/46.4.0/windows/windows_x64_64.exe"
          $installer = "gams_installer.exe"
          Invoke-WebRequest -Uri $url -OutFile $installer
          Start-Process $installer -ArgumentList "/silent" -NoNewWindow -Wait
          Remove-Item $installer
          $env:Path += ";C:\GAMS\46"
          [Environment]::SetEnvironmentVariable("Path", $env:Path, [EnvironmentVariableTarget]::Machine)
          echo $env:Path

      - name: Setup GAMS License
        env:
          LICENSE: ${{ secrets.GAMS_LICENSE }}
          
        run: |
          $licenseFile = "C:\GAMS\46\gamslice.txt"
          New-Item -ItemType Directory -Force -Path "C:\GAMS\46"
          Set-Content -Path $licenseFile -Value $env:LICENSE

      - name: Verify GAMS Installation
        run: |
          & "C:\GAMS\46\gams.exe"